# Site settings
title: Roku ERP管理系统
email: service@nppoly.net
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.nppoly.net" # the base hostname & protocol for your site

twitter_username:
github_username:
product_name: Roku ERP
brand: Roku

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

lang: zh-CN

google_analytics: UA-119554930-1

paginate: 8

